<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>SPANDigital</Authors>
    <Company>Span Digital</Company>
    <Product>Cel2Sql</Product>
    <Copyright>Copyright (c) 2026 Span Digital</Copyright>
    <RepositoryUrl>https://github.com/SPANDigital/Cel2Sql.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/SPANDigital/Cel2Sql.NET</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
